### ISSUE TITLE
helium branch not working (repo.sdnhub.org down)

### ISSUE THREAD

**Issue by lior789** [sdnhub/SDNHub_Opendaylight_Tutorial#9]
hi,
a while a go i used your your tutorial to develop a small research tool,
i used the AD-SAL version and openflow13 plugin

lately i tried to recompile  the code on a new machine,
i used the helium branch and found out it can't be built because maven can't get dependencies from repo.sdnhub.org.

does the repository is down forever? is there any other way to build a code that use the openflow13 AD-SAL plugin or my only solution is to convert my code to MD-SAL?

Thanks
lior

**Comment by srini084** [comment]
It is up now.  Can you retry?

**Comment by lior789** [comment]
it works!
thank you very much.
